"""
### Scenario: running the Python TCP client, testing with the server and RTT analysis in Wireshark

#### 1. Objective

In this stage you will:
- start the TCP Python server from the previous stage;
- run a simple TCP client (`index_tcp-client_example.py`);
- modify a client template to send messages in a loop and measure RTT;
- analyse the traffic in Wireshark and correlate packets with client/server logs.

---

### 2. Preparation: start the TCP server

Ensure that the server from the previous stage is running (e.g. the completed template variant):

```bash
python3 index_tcp-server_template.py
````

You should see:

```text
[INFO] TCP server listening on localhost:12345
```

---

### 3. Running the example client

1. In a separate terminal, run:

```bash
python3 index_tcp-client_example.py
```

2. Observe:

   * in the client terminal: the messages `[INFO] Connecting...`, then `Received b'...'`;
   * in the server terminal: the received and transformed message (e.g. `HELLO, WORLD`).

Repeat the command a few times and observe how separate TCP connections are opened and closed.

---

### 4. Capturing traffic with Wireshark

1. Open **Wireshark** and select the relevant interface (`lo`, `Loopback`, `eth0`, `wlan0`, etc.).

2. Set a **capture filter** to capture only the traffic destined for the server port:

```text
tcp port 12345
```

3. Start the capture.

4. Run the example client again:

```bash
python3 index_tcp-client_example.py
```

5. Stop the capture after the client has sent and received the message.

6. Apply a **display filter**:

```text
tcp.port == 12345
```

Analyse:

* the TCP handshake (SYN, SYN-ACK, ACK);
* the packet containing `Hello, world`;
* the server response packet (e.g. `HELLO, WORLD`).

---

### 5. Student task – interactive client + RTT

1. Open the file `index_tcp-client_template.py`.

2. Complete the marked section:

```python
# >>> STUDENT CODE STARTS HERE
...
# <<< STUDENT CODE ENDS HERE
```

following the requirements in the comments:

* read messages from the keyboard;
* stop when the `exit` command is entered;
* send the messages to the server;
* compute and display the RTT for each message.

3. Run the modified client:

```bash
python3 index_tcp-client_template.py
```

Send at least 5 different messages (of varying lengths).

4. Allow the server to display logs for each message.

---

### 6. Wireshark capture for the interactive client

1. Start a new capture in Wireshark with the same **capture filter**:

```text
tcp port 12345
```

2. While the capture is running, send the 5 messages from the interactive client.

3. Stop the capture and apply the display filter:

```text
tcp.port == 12345
```

4. For one of the messages:

   * identify the request packet (from client to server);
   * identify the response packet (from server to client);
   * note the time difference between them in Wireshark (Time delta).

Compare the approximate RTT value measured in code with the time interval from Wireshark.

---

### 7. Proof of work (what to submit)

1. Text file: `tcp_client_activity_output.txt` containing:

   * at least 3 client logs (message sent, response received, RTT);
   * 2–3 relevant server logs (received messages);
   * a brief commentary (5–7 sentences) about how the logs and Wireshark packets correlate.

2. Capture file: `tcp_client_capture.pcapng` with the traffic generated by the interactive client.
"""
